module.exports = [
  {
    id: 1,
   name: "Newspapers",
    type_id: 2,
    disposal_location: "Blue bin",
    instruction:
      "Ensure newspapers are clean and dry before placing them in the blue bin. Consider reusing or donating newspapers first.",
    unit: "Bundle",
    cmi: 0.8,
    landfill_g: 500,
  },
  {
    id: 2,
   name: "Cardboard Boxes",
    type_id: 2,
    disposal_location: "Blue bin",
    instruction:
      "Flatten cardboard boxes to save space and place them in the blue bin. Alternatively, reuse boxes for storage or shipping.",
    unit: "Box",
    cmi: 0.9,
    landfill_g: 1000,
  },
  {
    id: 3,
   name: "Office Paper",
    type_id: 2,
    disposal_location: "Blue bin",
    instruction:
      "Place clean and dry office paper in the blue bin. Consider using both sides of paper and opting for recycled paper products whenever possible.",
    unit: "Ream",
    cmi: 0.95,
    landfill_g: 800,
  },
  {
    id: 4,
   name: "Plastic Bottles",
    type_id: 1,
    disposal_location: "Blue bin",
    instruction:
      "Rinse and flatten plastic bottles, remove caps, and place them in the blue bin. Choose reusable water bottles to reduce waste.",
    unit: "Bottle",
    cmi: 0.5,
    landfill_g: 200,
  },
  {
    id: 5,
   name: "Plastic Bags",
    type_id: 1,
    disposal_location: "Retailer",
    instruction:
      "Return plastic bags to participating retailers for recycling. Use reusable shopping bags whenever possible to minimize plastic waste.",
    unit: "Bag",
    cmi: 0.1,
    landfill_g: 100,
  },
  {
    id: 6,
   name: "Milk Jugs",
    type_id: 1,
    disposal_location: "Blue bin",
    instruction:
      "Rinse milk jugs thoroughly and place them in the blue bin. Consider switching to reusable milk containers to reduce waste.",
    unit: "Jug",
    cmi: 0.6,
    landfill_g: 300,
  },
  {
    id: 7,
   name: "Aluminum Cans",
    type_id: 4,
    disposal_location: "Blue bin",
    instruction:
      "Rinse aluminum cans and place them in the blue bin. Aluminum is highly recyclable, so recycling it saves energy and resources.",
    unit: "Can",
    cmi: 0.9,
    landfill_g: 50,
  },
  {
    id: 8,
   name: "Steel Cans",
    type_id: 4,
    disposal_location: "Blue bin",
    instruction:
      "Rinse steel cans and place them in the blue bin. Steel is also highly recyclable and helps conserve natural resources.",
    unit: "Can",
    cmi: 0.85,
    landfill_g: 100,
  },
  {
    id: 9,
   name: "Tin Foil",
    type_id: 4,
    disposal_location: "Blue bin",
    instruction:
      "Ball up tin foil to avoid it getting lost in sorting and place it in the blue bin. Consider using reusable containers to avoid foil waste.",
    unit: "Roll",
    cmi: 0.7,
    landfill_g: 20,
  },
  {
    id: 10,
   name: "Glass Bottles",
    type_id: 3,
    disposal_location: "Blue bin",
    instruction:
      "Rinse glass bottles and remove lids before placing them in the blue bin. Glass is infinitely recyclable without losing quality.",
    unit: "Bottle",
    cmi: 0.8,
    landfill_g: 500,
  },
  {
    id: 11,
   name: "Glass Jars",
    type_id: 3,
    disposal_location: "Blue bin",
    instruction:
      "Remove lids and place glass jars in the blue bin. Glass is infinitely recyclable without losing quality.",
    unit: "Jar",
    cmi: 0.85,
    landfill_g: 400,
  },
  {
    id: 12,
   name: "Old Clothing",
    type_id: 7,
    disposal_location: "Donation bin",
    instruction:
      "Donate usable clothing to charity or textile recycling programs. Torn or unusable clothing can be repurposed as rags.",
    unit: "Item",
    cmi: 0.4,
    landfill_g: 600,
  },
  {
    id: 13,
   name: "Towels & Linens",
    type_id: 7,
    disposal_location: "Donation bin or textile recycling",
    instruction:
      "Donate usable towels and linens or take them to a textile recycling center. Consider composting old, natural fiber linens.",
    unit: "Item",
    cmi: 0.35,
    landfill_g: 500,
  },
  {
    id: 14,
   name: "Old Phones",
    type_id: 6,
    disposal_location: "E-waste collection center",
    instruction:
      "Take to your local e-waste collection center for responsible recycling and disposal. Consider donating or selling working phones to extend their lifespan.",
    unit: "Item",
    cmi: 0.6,
    landfill_g: 150,
  },
  {
    id: 15,
   name: "Batteries",
    type_id: 6,
    disposal_location: "Battery collection",
    instruction:
      "Take batteries to designated battery collection points. Never dispose of batteries in household trash or recycling as they contain harmful chemicals.",
    unit: "Item",
    cmi: 0.7,
    landfill_g: 50,
  },
  {
    id: 16,
   name: "Light Bulbs",
    type_id: 6,
    disposal_location: "Designated drop-off",
    instruction:
      "Take light bulbs to a designated drop-off location or hardware store that accepts them. Different types of bulbs may require different disposal methods.",
    unit: "Bulb",
    cmi: 0.3,
    landfill_g: 10,
  },
  {
    id: 17,
   name: "Food Scraps",
    type_id: 5,
    disposal_location: "Compost bin or green bin",
    instruction:
      "Place food scraps in your compost bin or green bin to turn them into nutrient-rich compost for your garden.",
    unit: "Kilogram",
    cmi: 1.0,
    landfill_g: 500,
  },
  {
    id: 18,
   name: "Yard Waste",
    type_id: 5,
    disposal_location: "Green bin or yard waste collection",
    instruction:
      "Place yard waste in your green bin or schedule a yard waste collection with your municipality. Consider home composting if possible.",
    unit: "Bag",
    cmi: 1.0,
    landfill_g: 2000,
  },
  {
    id: 19,
   name: "Coffee Grounds",
    type_id: 5,
    disposal_location: "Green bin",
    instruction:
      "Add coffee grounds to your compost bin or green bin. They are a great source of nitrogen for your compost.",
    unit: "Cup",
    cmi: 1.0,
    landfill_g: 100,
  },
  {
    id: 20,
   name: "Eggshells",
    type_id: 5,
    disposal_location: "Compost bin",
    instruction:
      "Crush eggshells and add them to your compost bin. They provide calcium and other nutrients for your plants.",
    unit: "Shell",
    cmi: 1.0,
    landfill_g: 10,
  },
  {
    id: 21,
   name: "Paint",
    type_id: 6,
    disposal_location: "Hazardous waste collection",
    instruction:
      "Take leftover paint to a hazardous waste collection facility. Never pour paint down the drain or into storm sewers.",
    unit: "Can",
    cmi: 0.2,
    landfill_g: 1000,
  },
  {
    id: 22,
   name: "Cleaning Products",
    type_id: 6,
    disposal_location: "Hazardous waste collection",
    instruction:
      "Empty containers may be recyclable; check local guidelines. Take leftover cleaning products to a hazardous waste collection facility.",
    unit: "Bottle",
    cmi: 0.2,
    landfill_g: 300,
  },
  {
    id: 23,
   name: "Pesticides",
    type_id: 6,
    disposal_location: "Hazardous waste collection",
    instruction:
      "Take unused pesticides to a hazardous waste collection facility. Do not dispose of pesticides in household trash or down the drain as they can contaminate soil and water.",
    unit: "Container",
    cmi: 0.1,
    landfill_g: 200,
  },
  {
    id: 24,
   name: "Plastic Water Bottles",
    type_id: 1,
    disposal_location: "Blue bin",
    instruction:
      "Rinse and flatten plastic bottles, remove caps, and place them in the blue bin. Choose reusable water bottles to reduce waste.",
    unit: "Bottle",
    cmi: 0.5,
    landfill_g: 200,
  },
  {
    id: 25,
   name: "Plastic Grocery Bags",
    type_id: 1,
    disposal_location: "Blue Bin",
    instruction:
      "Return plastic bags to participating retailers for recycling. Use reusable shopping bags whenever possible to minimize plastic waste.",
    unit: "Bag",
    cmi: 0.1,
    landfill_g: 100,
  },
  {
    id: 26,
   name: "Plastic Straws",
    type_id: 1,
    disposal_location: "Garbage",
    instruction:
      "Place in garbage bin. Consider using reusable or paper straws to reduce plastic waste.",
    unit: "Straw",
    cmi: 0.05,
    landfill_g: 10,
  },
  {
    id: 27,
   name: "Plastic Cutlery",
    type_id: 1,
    disposal_location: "Garbage",
    instruction:
      "Place in garbage bin. Consider using reusable cutlery to reduce plastic waste.",
    unit: "Set",
    cmi: 0.05,
    landfill_g: 30,
  },
  {
    id: 28,
   name: "Plastic Food Containers",
    type_id: 1,
    disposal_location: "Blue bin",
    instruction:
      "Rinse and place in blue bin if clean, otherwise place in garbage bin.",
    unit: "Container",
    cmi: 0.5,
    landfill_g: 150,
  },
  {
    id: 29,
   name: "Plastic Cups",
    type_id: 1,
    disposal_location: "Blue bin",
    instruction:
      "Rinse and place in blue bin. Opt for reusable cups to reduce plastic waste.",
    unit: "Cup",
    cmi: 0.4,
    landfill_g: 80,
  },
  {
    id: 30,
   name: "Plastic Packaging (e.g., Wrappers)",
    type_id: 1,
    disposal_location: "Garbage",
    instruction:
      "Place in garbage bin. Choose products with minimal packaging to reduce waste.",
    unit: "Item",
    cmi: 0.1,
    landfill_g: 50,
  },
  {
    id: 31,
   name: "Plastic Lids",
    type_id: 1,
    disposal_location: "Blue bin",
    instruction: "Rinse and place in blue bin.",
    unit: "Lid",
    cmi: 0.3,
    landfill_g: 20,
  },
  {
    id: 32,
   name: "Plastic Beverage Rings",
    type_id: 1,
    disposal_location: "Garbage",
    instruction:
      "Cut into pieces before placing in garbage bin to prevent wildlife entanglement.",
    unit: "Ring",
    cmi: 0.05,
    landfill_g: 15,
  },
  {
    id: 33,
   name: "Styrofoam (Polystyrene) Cups",
    type_id: 1,
    disposal_location: "Garbage",
    instruction:
      "Place in garbage bin. Consider using reusable cups to reduce Styrofoam waste.",
    unit: "Cup",
    cmi: 0.01,
    landfill_g: 50,
  },
  {
    id: 34,
   name: "Plastic Plates",
    type_id: 1,
    disposal_location: "Garbage",
    instruction:
      "Place in garbage bin. Consider using reusable plates to reduce plastic waste.",
    unit: "Plate",
    cmi: 0.05,
    landfill_g: 40,
  },
  {
    id: 35,
   name: "Plastic Sachets",
    type_id: 1,
    disposal_location: "Garbage",
    instruction:
      "Place in garbage bin. Choose products with less packaging to reduce waste.",
    unit: "Sachet",
    cmi: 0.01,
    landfill_g: 10,
  },
];
