module.exports = [
  {
    id: 1,
    productName: "Newspapers",
    type_id: 2,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Ensure newspapers are clean and dry before placing them in the blue bin. Consider reusing or donating newspapers first.",
    unit: "Bundle",
    circularMaterialIndex: 0.8,
    landfillContributionG: 500,
  },
  {
    id: 2,
    productName: "Cardboard Boxes",
    type_id: 2,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Flatten cardboard boxes to save space and place them in the blue bin. Alternatively, reuse boxes for storage or shipping.",
    unit: "Box",
    circularMaterialIndex: 0.9,
    landfillContributionG: 1000,
  },
  {
    id: 3,
    productName: "Office Paper",
    type_id: 2,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Place clean and dry office paper in the blue bin. Consider using both sides of paper and opting for recycled paper products whenever possible.",
    unit: "Ream",
    circularMaterialIndex: 0.95,
    landfillContributionG: 800,
  },
  {
    id: 4,
    productName: "Plastic Bottles",
    type_id: 1,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Rinse and flatten plastic bottles, remove caps, and place them in the blue bin. Choose reusable water bottles to reduce waste.",
    unit: "Bottle",
    circularMaterialIndex: 0.5,
    landfillContributionG: 200,
  },
  {
    id: 5,
    productName: "Plastic Bags",
    type_id: 1,
    disposalLocation: "Retailer",
    disposalInstructions:
      "Return plastic bags to participating retailers for recycling. Use reusable shopping bags whenever possible to minimize plastic waste.",
    unit: "Bag",
    circularMaterialIndex: 0.1,
    landfillContributionG: 100,
  },
  {
    id: 6,
    productName: "Milk Jugs",
    type_id: 1,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Rinse milk jugs thoroughly and place them in the blue bin. Consider switching to reusable milk containers to reduce waste.",
    unit: "Jug",
    circularMaterialIndex: 0.6,
    landfillContributionG: 300,
  },
  {
    id: 7,
    productName: "Aluminum Cans",
    type_id: 4,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Rinse aluminum cans and place them in the blue bin. Aluminum is highly recyclable, so recycling it saves energy and resources.",
    unit: "Can",
    circularMaterialIndex: 0.9,
    landfillContributionG: 50,
  },
  {
    id: 8,
    productName: "Steel Cans",
    type_id: 4,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Rinse steel cans and place them in the blue bin. Steel is also highly recyclable and helps conserve natural resources.",
    unit: "Can",
    circularMaterialIndex: 0.85,
    landfillContributionG: 100,
  },
  {
    id: 9,
    productName: "Tin Foil",
    type_id: 4,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Ball up tin foil to avoid it getting lost in sorting and place it in the blue bin. Consider using reusable containers to avoid foil waste.",
    unit: "Roll",
    circularMaterialIndex: 0.7,
    landfillContributionG: 20,
  },
  {
    id: 10,
    productName: "Glass Bottles",
    type_id: 3,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Rinse glass bottles and remove lids before placing them in the blue bin. Glass is infinitely recyclable without losing quality.",
    unit: "Bottle",
    circularMaterialIndex: 0.8,
    landfillContributionG: 500,
  },
  {
    id: 11,
    productName: "Glass Jars",
    type_id: 3,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Remove lids and place glass jars in the blue bin. Glass is infinitely recyclable without losing quality.",
    unit: "Jar",
    circularMaterialIndex: 0.85,
    landfillContributionG: 400,
  },
  {
    id: 12,
    productName: "Old Clothing",
    type_id: 7,
    disposalLocation: "Donation bin",
    disposalInstructions:
      "Donate usable clothing to charity or textile recycling programs. Torn or unusable clothing can be repurposed as rags.",
    unit: "Item",
    circularMaterialIndex: 0.4,
    landfillContributionG: 600,
  },
  {
    id: 13,
    productName: "Towels & Linens",
    type_id: 7,
    disposalLocation: "Donation bin or textile recycling",
    disposalInstructions:
      "Donate usable towels and linens or take them to a textile recycling center. Consider composting old, natural fiber linens.",
    unit: "Item",
    circularMaterialIndex: 0.35,
    landfillContributionG: 500,
  },
  {
    id: 14,
    productName: "Old Phones",
    type_id: 6,
    disposalLocation: "E-waste collection center",
    disposalInstructions:
      "Take to your local e-waste collection center for responsible recycling and disposal. Consider donating or selling working phones to extend their lifespan.",
    unit: "Item",
    circularMaterialIndex: 0.6,
    landfillContributionG: 150,
  },
  {
    id: 15,
    productName: "Batteries",
    type_id: 6,
    disposalLocation: "Battery collection",
    disposalInstructions:
      "Take batteries to designated battery collection points. Never dispose of batteries in household trash or recycling as they contain harmful chemicals.",
    unit: "Item",
    circularMaterialIndex: 0.7,
    landfillContributionG: 50,
  },
  {
    id: 16,
    productName: "Light Bulbs",
    type_id: 6,
    disposalLocation: "Designated drop-off",
    disposalInstructions:
      "Take light bulbs to a designated drop-off location or hardware store that accepts them. Different types of bulbs may require different disposal methods.",
    unit: "Bulb",
    circularMaterialIndex: 0.3,
    landfillContributionG: 10,
  },
  {
    id: 17,
    productName: "Food Scraps",
    type_id: 5,
    disposalLocation: "Compost bin or green bin",
    disposalInstructions:
      "Place food scraps in your compost bin or green bin to turn them into nutrient-rich compost for your garden.",
    unit: "Kilogram",
    circularMaterialIndex: 1.0,
    landfillContributionG: 500,
  },
  {
    id: 18,
    productName: "Yard Waste",
    type_id: 5,
    disposalLocation: "Green bin or yard waste collection",
    disposalInstructions:
      "Place yard waste in your green bin or schedule a yard waste collection with your municipality. Consider home composting if possible.",
    unit: "Bag",
    circularMaterialIndex: 1.0,
    landfillContributionG: 2000,
  },
  {
    id: 19,
    productName: "Coffee Grounds",
    type_id: 5,
    disposalLocation: "Compost bin or green bin",
    disposalInstructions:
      "Add coffee grounds to your compost bin or green bin. They are a great source of nitrogen for your compost.",
    unit: "Cup",
    circularMaterialIndex: 1.0,
    landfillContributionG: 100,
  },
  {
    id: 20,
    productName: "Eggshells",
    type_id: 5,
    disposalLocation: "Compost bin",
    disposalInstructions:
      "Crush eggshells and add them to your compost bin. They provide calcium and other nutrients for your plants.",
    unit: "Shell",
    circularMaterialIndex: 1.0,
    landfillContributionG: 10,
  },
  {
    id: 21,
    productName: "Paint",
    type_id: 6,
    disposalLocation: "Hazardous waste collection",
    disposalInstructions:
      "Take leftover paint to a hazardous waste collection facility. Never pour paint down the drain or into storm sewers.",
    unit: "Can",
    circularMaterialIndex: 0.2,
    landfillContributionG: 1000,
  },
  {
    id: 22,
    productName: "Cleaning Products",
    type_id: 6,
    disposalLocation: "Hazardous waste collection",
    disposalInstructions:
      "Empty containers may be recyclable; check local guidelines. Take leftover cleaning products to a hazardous waste collection facility.",
    unit: "Bottle",
    circularMaterialIndex: 0.2,
    landfillContributionG: 300,
  },
  {
    id: 23,
    productName: "Pesticides",
    type_id: 6,
    disposalLocation: "Hazardous waste collection",
    disposalInstructions:
      "Take unused pesticides to a hazardous waste collection facility. Do not dispose of pesticides in household trash or down the drain as they can contaminate soil and water.",
    unit: "Container",
    circularMaterialIndex: 0.1,
    landfillContributionG: 200,
  },
  {
    id: 24,
    productName: "Plastic Water Bottles",
    type_id: 1,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Rinse and flatten plastic bottles, remove caps, and place them in the blue bin. Choose reusable water bottles to reduce waste.",
    unit: "Bottle",
    circularMaterialIndex: 0.5,
    landfillContributionG: 200,
  },
  {
    id: 25,
    productName: "Plastic Grocery Bags",
    type_id: 1,
    disposalLocation: "Retailer",
    disposalInstructions:
      "Return plastic bags to participating retailers for recycling. Use reusable shopping bags whenever possible to minimize plastic waste.",
    unit: "Bag",
    circularMaterialIndex: 0.1,
    landfillContributionG: 100,
  },
  {
    id: 26,
    productName: "Plastic Straws",
    type_id: 1,
    disposalLocation: "Garbage",
    disposalInstructions:
      "Place in garbage bin. Consider using reusable or paper straws to reduce plastic waste.",
    unit: "Straw",
    circularMaterialIndex: 0.05,
    landfillContributionG: 10,
  },
  {
    id: 27,
    productName: "Plastic Cutlery",
    type_id: 1,
    disposalLocation: "Garbage",
    disposalInstructions:
      "Place in garbage bin. Consider using reusable cutlery to reduce plastic waste.",
    unit: "Set",
    circularMaterialIndex: 0.05,
    landfillContributionG: 30,
  },
  {
    id: 28,
    productName: "Plastic Food Containers",
    type_id: 1,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Rinse and place in blue bin if clean, otherwise place in garbage bin.",
    unit: "Container",
    circularMaterialIndex: 0.5,
    landfillContributionG: 150,
  },
  {
    id: 29,
    productName: "Plastic Cups",
    type_id: 1,
    disposalLocation: "Blue bin",
    disposalInstructions:
      "Rinse and place in blue bin. Opt for reusable cups to reduce plastic waste.",
    unit: "Cup",
    circularMaterialIndex: 0.4,
    landfillContributionG: 80,
  },
  {
    id: 30,
    productName: "Plastic Packaging (e.g., Wrappers)",
    type_id: 1,
    disposalLocation: "Garbage",
    disposalInstructions:
      "Place in garbage bin. Choose products with minimal packaging to reduce waste.",
    unit: "Item",
    circularMaterialIndex: 0.1,
    landfillContributionG: 50,
  },
  {
    id: 31,
    productName: "Plastic Lids",
    type_id: 1,
    disposalLocation: "Blue bin",
    disposalInstructions: "Rinse and place in blue bin.",
    unit: "Lid",
    circularMaterialIndex: 0.3,
    landfillContributionG: 20,
  },
  {
    id: 32,
    productName: "Plastic Beverage Rings",
    type_id: 1,
    disposalLocation: "Garbage",
    disposalInstructions:
      "Cut into pieces before placing in garbage bin to prevent wildlife entanglement.",
    unit: "Ring",
    circularMaterialIndex: 0.05,
    landfillContributionG: 15,
  },
  {
    id: 33,
    productName: "Styrofoam (Polystyrene) Cups",
    type_id: 1,
    disposalLocation: "Garbage",
    disposalInstructions:
      "Place in garbage bin. Consider using reusable cups to reduce Styrofoam waste.",
    unit: "Cup",
    circularMaterialIndex: 0.01,
    landfillContributionG: 50,
  },
  {
    id: 34,
    productName: "Plastic Plates",
    type_id: 1,
    disposalLocation: "Garbage",
    disposalInstructions:
      "Place in garbage bin. Consider using reusable plates to reduce plastic waste.",
    unit: "Plate",
    circularMaterialIndex: 0.05,
    landfillContributionG: 40,
  },
  {
    id: 35,
    productName: "Plastic Sachets",
    type_id: 1,
    disposalLocation: "Garbage",
    disposalInstructions:
      "Place in garbage bin. Choose products with less packaging to reduce waste.",
    unit: "Sachet",
    circularMaterialIndex: 0.01,
    landfillContributionG: 10,
  },
];
