module.exports = [
  {
    id: 1,
    type_id: 2,
    name: "Newspapers",
    designation: "Blue bin",
    instruction:
      "Ensure newspapers are clean and dry before placing them in the blue bin. Consider reusing or donating newspapers first.",
    reusable: "high",
    recyclable: "high",
    unit: "Bundle",
    weight_g: 500,
    circular_material_index: 0.8,
  },
  {
    id: 2,
    type_id: 2,
    name: "Cardboard Boxes",
    designation: "Blue bin",
    instruction:
      "Flatten cardboard boxes to save space and place them in the blue bin. Alternatively, reuse boxes for storage or shipping.",
    reusable: "high",
    recyclable: "high",
    unit: "Box",
    weight_g: 1000,
    circular_material_index: 0.9,
  },
  {
    id: 3,
    type_id: 2,
    name: "Office Paper",
    designation: "Blue bin",
    instruction:
      "Place clean and dry office paper in the blue bin. Consider using both sides of paper and opting for recycled paper products whenever possible.",
    reusable: "high",
    recyclable: "high",
    unit: "Ream",
    weight_g: 800,
    circular_material_index: 0.95,
  },
  {
    id: 4,
    type_id: 1,
    name: "Plastic Bottles",
    designation: "Blue bin",
    instruction:
      "Rinse and flatten plastic bottles, remove caps, and place them in the blue bin. Choose reusable water bottles to reduce waste.",
    reusable: "low",
    recyclable: "high",
    unit: "Bottle",
    weight_g: 200,
    circular_material_index: 0.5,
  },
  {
    id: 5,
    type_id: 1,
    name: "Plastic Bags",
    designation: "Landfill",
    instruction:
      "Return plastic bags to participating retailers for recycling. Use reusable shopping bags whenever possible to minimize plastic waste.",
    reusable: "low",
    recyclable: "low",
    unit: "Bag",
    weight_g: 100,
    circular_material_index: 0.1,
  },
  {
    id: 6,
    type_id: 1,
    name: "Milk Jugs",
    designation: "Blue bin",
    instruction:
      "Rinse milk jugs thoroughly and place them in the blue bin. Consider switching to reusable milk containers to reduce waste.",
    reusable: "low",
    recyclable: "high",
    unit: "Jug",
    weight_g: 300,
    circular_material_index: 0.6,
  },
  {
    id: 7,
    type_id: 4,
    name: "Aluminum Cans",
    designation: "Blue bin",
    instruction:
      "Rinse aluminum cans and place them in the blue bin. Aluminum is highly recyclable, so recycling it saves energy and resources.",
    reusable: "low",
    recyclable: "high",
    unit: "Can",
    weight_g: 50,
    circular_material_index: 0.9,
  },
  {
    id: 8,
    type_id: 4,
    name: "Steel Cans",
    designation: "Blue bin",
    instruction:
      "Rinse steel cans and place them in the blue bin. Steel is also highly recyclable and helps conserve natural resources.",
    reusable: "low",
    recyclable: "high",
    unit: "Can",
    weight_g: 100,
    circular_material_index: 0.85,
  },
  {
    id: 9,
    type_id: 4,
    name: "Tin Foil",
    designation: "Blue bin",
    instruction:
      "Ball up tin foil to avoid it getting lost in sorting and place it in the blue bin. Consider using reusable containers to avoid foil waste.",
    reusable: "low",
    recyclable: "high",
    unit: "Roll",
    weight_g: 20,
    circular_material_index: 0.7,
  },
  {
    id: 10,
    type_id: 3,
    name: "Glass Bottles",
    designation: "Blue bin",
    instruction:
      "Rinse glass bottles and remove lids before placing them in the blue bin. Glass is infinitely recyclable without losing quality.",
    reusable: "low",
    recyclable: "high",
    unit: "Bottle",
    weight_g: 500,
    circular_material_index: 0.8,
  },
  {
    id: 11,
    type_id: 3,
    name: "Glass Jars",
    designation: "Blue bin",
    instruction:
      "Remove lids and place glass jars in the blue bin. Glass is infinitely recyclable without losing quality.",
    reusable: "low",
    recyclable: "high",
    unit: "Jar",
    weight_g: 400,
    circular_material_index: 0.85,
  },
  {
    id: 12,
    type_id: 7,
    name: "Old Clothing",
    designation: "Donation bin",
    instruction:
      "Donate usable clothing to charity or textile recycling programs. Torn or unusable clothing can be repurposed as rags.",
    reusable: "high",
    recyclable: "low",
    unit: "Item",
    weight_g: 600,
    circular_material_index: 0.4,
  },
  {
    id: 13,
    type_id: 7,
    name: "Towels & Linens",
    designation: "Donation bin or textile recycling",
    instruction:
      "Donate usable towels and linens or take them to a textile recycling center. Consider composting old, natural fiber linens.",
    reusable: "high",
    recyclable: "low",
    unit: "Item",
    weight_g: 500,
    circular_material_index: 0.35,
  },
  {
    id: 14,
    type_id: 6,
    name: "Old Phones",
    designation: "E-waste collection center",
    instruction:
      "Take to your local e-waste collection center for responsible recycling and disposal. Consider donating or selling working phones to extend their lifespan.",
    reusable: "high",
    recyclable: "high",
    unit: "Item",
    weight_g: 150,
    circular_material_index: 0.6,
  },
  {
    id: 15,
    type_id: 6,
    name: "Batteries",
    designation: "Battery collection",
    instruction:
      "Take batteries to designated battery collection points. Never dispose of batteries in household trash or recycling as they contain harmful chemicals.",
    reusable: "low",
    recyclable: "high",
    unit: "Item",
    weight_g: 50,
    circular_material_index: 0.7,
  },
  {
    id: 16,
    type_id: 6,
    name: "Light Bulbs",
    designation: "E-waste drop-off",
    instruction:
      "Take light bulbs to a designated drop-off location or hardware store that accepts them. Different types of bulbs may require different disposal methods.",
    reusable: "low",
    recyclable: "low",
    unit: "Bulb",
    weight_g: 10,
    circular_material_index: 0.3,
  },
  {
    id: 17,
    type_id: 5,
    name: "Food Scraps",
    designation: "Compost bin or green bin",
    instruction:
      "Place food scraps in your compost bin or green bin to turn them into nutrient-rich compost for your garden.",
    reusable: "low",
    recyclable: "high",
    unit: "Kilogram",
    weight_g: 500,
    circular_material_index: 1.0,
  },
  {
    id: 18,
    type_id: 5,
    name: "Yard Waste",
    designation: "Green bin or yard waste collection",
    instruction:
      "Place yard waste in your green bin or schedule a yard waste collection with your local waste management service. Consider mulching if possible.",
    reusable: "low",
    recyclable: "high",
    unit: "Bag",
    weight_g: 2000,
    circular_material_index: 1.0,
  },
  {
    id: 19,
    type_id: 5,
    name: "Coffee Grounds",
    designation: "Green bin",
    instruction:
      "Add coffee grounds to your compost bin or green bin. They are a great source of nitrogen for your compost.",
    reusable: "low",
    recyclable: "high",
    unit: "Cup",
    weight_g: 100,
    circular_material_index: 1.0,
  },
  {
    id: 20,
    type_id: 5,
    name: "Eggshells",
    designation: "Green bin",
    instruction:
      "Crush eggshells and add them to your compost bin. They provide calcium and other nutrients for your plants.",
    reusable: "low",
    recyclable: "high",
    unit: "Shell",
    weight_g: 10,
    circular_material_index: 1.0,
  },
  {
    id: 21,
    type_id: 6,
    name: "Paint",
    designation: "Hazardous waste collection",
    instruction:
      "Take leftover paint to a hazardous waste collection facility. Never pour paint down the drain or into storm sewers.",
    reusable: "low",
    recyclable: "low",
    unit: "Can",
    weight_g: 1000,
    circular_material_index: 0.2,
  },
  {
    id: 22,
    type_id: 6,
    name: "Cleaning Products",
    designation: "Blue Bin",
    instruction:
      "Empty containers may be recyclable; check local guidelines. Take leftover cleaning products to a hazardous waste collection facility.",
    reusable: "low",
    recyclable: "low",
    unit: "Bottle",
    weight_g: 300,
    circular_material_index: 0.2,
  },
  {
    id: 23,
    type_id: 6,
    name: "Battery",
    designation: "E-waste collection point",
    instruction:
      "Take used batteries to a battery recycling center or a designated collection point (often found in retail stores). Do not dispose of batteries in household trash as they contain hazardous materials.",
    reusable: "low",
    recyclable: "high",
    unit: "Each",
    weight_g: 15,
    circular_material_index: 0.6,
  },
  {
    id: 24,
    type_id: 1,
    name: "Plastic Water Bottles",
    designation: "Blue bin",
    instruction:
      "Rinse and flatten plastic bottles, remove caps, and place them in the blue bin. Choose reusable water bottles to reduce waste.",
    reusable: "low",
    recyclable: "high",
    unit: "Bottle",
    weight_g: 200,
    circular_material_index: 0.5,
  },
  {
    id: 25,
    type_id: 1,
    name: "Plastic Grocery Bags",
    designation: "Blue Bin",
    instruction:
      "Return plastic bags to participating retailers for recycling. Use reusable shopping bags whenever possible to minimize plastic waste.",
    reusable: "low",
    recyclable: "low",
    unit: "Bag",
    weight_g: 100,
    circular_material_index: 0.1,
  },
  {
    id: 26,
    type_id: 1,
    name: "Plastic Straws",
    designation: "Garbage",
    instruction:
      "Place in garbage bin. Consider using reusable or paper straws to reduce plastic waste.",
    reusable: "low",
    recyclable: "low",
    unit: "Straw",
    weight_g: 10,
    circular_material_index: 0.05,
  },
  {
    id: 27,
    type_id: 1,
    name: "Plastic Cutlery",
    designation: "Garbage",
    instruction:
      "Place in garbage bin. Consider using reusable cutlery to reduce plastic waste.",
    reusable: "low",
    recyclable: "low",
    unit: "Set",
    weight_g: 30,
    circular_material_index: 0.05,
  },
  {
    id: 28,
    type_id: 1,
    name: "Plastic Food Containers",
    designation: "Blue bin",
    instruction:
      "Rinse and place in blue bin if clean, otherwise place in garbage bin.",
    reusable: "low",
    recyclable: "high",
    unit: "Container",
    weight_g: 150,
    circular_material_index: 0.5,
  },
  {
    id: 29,
    type_id: 1,
    name: "Plastic Cups",
    designation: "Blue bin",
    instruction:
      "Rinse and place in blue bin. Opt for reusable cups to reduce plastic waste.",
    reusable: "low",
    recyclable: "high",
    unit: "Cup",
    weight_g: 80,
    circular_material_index: 0.4,
  },
  {
    id: 30,
    type_id: 1,
    name: "Plastic Packaging (e.g., Wrappers)",
    designation: "Garbage",
    instruction:
      "Place in garbage bin. Choose products with minimal packaging to reduce waste.",
    reusable: "low",
    recyclable: "low",
    unit: "Item",
    weight_g: 50,
    circular_material_index: 0.1,
  },
  {
    id: 31,
    type_id: 1,
    name: "Plastic Lids",
    designation: "Blue bin",
    instruction: "Rinse and place in blue bin.",
    reusable: "low",
    recyclable: "high",
    unit: "Lid",
    weight_g: 20,
    circular_material_index: 0.3,
  },
  {
    id: 32,
    type_id: 1,
    name: "Plastic Beverage Rings",
    designation: "Garbage",
    instruction:
      "Cut into pieces before placing in garbage bin to prevent wildlife entanglement.",
    reusable: "low",
    recyclable: "low",
    unit: "Ring",
    weight_g: 15,
    circular_material_index: 0.05,
  },
  {
    id: 33,
    type_id: 1,
    name: "Styrofoam (Polystyrene) Cups",
    designation: "Garbage",
    instruction:
      "Place in garbage bin. Consider using reusable cups to reduce Styrofoam waste.",
    reusable: "low",
    recyclable: "low",
    unit: "Cup",
    weight_g: 50,
    circular_material_index: 0.01,
  },
  {
    id: 34,
    type_id: 1,
    name: "Plastic Plates",
    designation: "Garbage",
    instruction:
      "Place in garbage bin. Consider using reusable plates to reduce plastic waste.",
    reusable: "low",
    recyclable: "low",
    unit: "Plate",
    weight_g: 40,
    circular_material_index: 0.05,
  },
  {
    id: 35,
    type_id: 1,
    name: "Plastic Sachets",
    designation: "Garbage",
    instruction:
      "Place in garbage bin. Choose products with less packaging to reduce waste.",
    reusable: "low",
    recyclable: "low",
    unit: "Sachet",
    weight_g: 10,
    circular_material_index: 0.01,
  },
  {
    id: 36,
    type_id: 6,
    name: "Printer Cartridges",
    designation: "E-waste collection point",
    instruction:
      "Return used printer cartridges to designated e-waste collection points or participating retailers.",
    reusable: "low",
    recyclable: "high",
    unit: "Cartridge",
    weight_g: 200,
    circular_material_index: 0.7,
  },
  {
    id: 37,
    type_id: 6,
    name: "Compact Fluorescent Bulbs",
    designation: "Hazardous waste collection",
    instruction:
      "Take to a hazardous waste collection point due to the mercury content. Handle with care.",
    reusable: "low",
    recyclable: "high",
    unit: "Bulb",
    weight_g: 150,
    circular_material_index: 0.5,
  },
  {
    id: 38,
    type_id: 6,
    name: "Televisions",
    designation: "E-waste collection point",
    instruction:
      "Take old televisions to an e-waste collection point for proper recycling. Consider donating working televisions.",
    reusable: "high",
    recyclable: "high",
    unit: "Item",
    weight_g: 8000,
    circular_material_index: 0.8,
  },
  {
    id: 39,
    type_id: 6,
    name: "Computers",
    designation: "E-waste collection point",
    instruction:
      "Take old computers to an e-waste collection point for proper recycling. Consider donating working computers.",
    reusable: "high",
    recyclable: "high",
    unit: "Item",
    weight_g: 5000,
    circular_material_index: 0.8,
  },
  {
    id: 40,
    type_id: 6,
    name: "Monitors",
    designation: "E-waste collection point",
    instruction:
      "Take old monitors to an e-waste collection point for proper recycling. Consider donating working monitors.",
    reusable: "high",
    recyclable: "high",
    unit: "Item",
    weight_g: 3000,
    circular_material_index: 0.75,
  },
  {
    id: 41,
    type_id: 6,
    name: "Tablets",
    designation: "E-waste collection point",
    instruction:
      "Take old tablets to an e-waste collection point for proper recycling. Consider donating working tablets.",
    reusable: "high",
    recyclable: "high",
    unit: "Item",
    weight_g: 500,
    circular_material_index: 0.7,
  },
  {
    id: 42,
    type_id: 6,
    name: "Small Appliances",
    designation: "E-waste collection point",
    instruction:
      "Take old small appliances to an e-waste collection point for proper recycling. Consider donating working appliances.",
    reusable: "high",
    recyclable: "high",
    unit: "Item",
    weight_g: 2000,
    circular_material_index: 0.7,
  },
  {
    id: 43,
    type_id: 7,
    name: "Shoes",
    designation: "Donation bin",
    instruction:
      "Donate usable shoes or place them in the garbage bin if they are not reusable.",
    reusable: "high",
    recyclable: "low",
    unit: "Pair",
    weight_g: 700,
    circular_material_index: 0.3,
  },
  {
    id: 44,
    type_id: 7,
    name: "Tires",
    designation: "Tire collection facility",
    instruction: "Take old tires to a tire collection facility for recycling.",
    reusable: "low",
    recyclable: "high",
    unit: "Tire",
    weight_g: 10000,
    circular_material_index: 0.85,
  },
  {
    id: 45,
    type_id: 7,
    name: "Bedding",
    designation: "Donation bin",
    instruction:
      "Donate usable bedding to charity or textile recycling programs. Torn or unusable bedding can be repurposed as rags.",
    reusable: "high",
    recyclable: "low",
    unit: "Item",
    weight_g: 1500,
    circular_material_index: 0.4,
  },
  {
    id: 46,
    type_id: 7,
    name: "Furniture",
    designation: "Donation center or bulk waste",
    instruction:
      "Donate usable furniture to a donation center or schedule a bulk waste collection for large items.",
    reusable: "high",
    recyclable: "low",
    unit: "Item",
    weight_g: 20000,
    circular_material_index: 0.5,
  },
  {
    id: 47,
    type_id: 5,
    name: "Used Paper Towels",
    designation: "Compost bin",
    instruction:
      "Place used paper towels in the compost bin if they are free of chemicals.",
    reusable: "low",
    recyclable: "high",
    unit: "Item",
    weight_g: 15,
    circular_material_index: 0.9,
  },
  {
    id: 48,
    type_id: 5,
    name: "Tea Bags",
    designation: "Compost bin",
    instruction: "Remove any staples and place tea bags in the compost bin.",
    reusable: "low",
    recyclable: "high",
    unit: "Bag",
    weight_g: 5,
    circular_material_index: 1.0,
  },
  {
    id: 49,
    type_id: 5,
    name: "Fruit Peels",
    designation: "Compost bin",
    instruction:
      "Place fruit peels in the compost bin. They decompose quickly and add valuable nutrients to the compost.",
    reusable: "low",
    recyclable: "high",
    unit: "Kilogram",
    weight_g: 300,
    circular_material_index: 1.0,
  },
  {
    id: 50,
    type_id: 5,
    name: "Vegetable Peels",
    designation: "Compost bin",
    instruction:
      "Place vegetable peels in the compost bin. They decompose quickly and add valuable nutrients to the compost.",
    reusable: "low",
    recyclable: "high",
    unit: "Kilogram",
    weight_g: 300,
    circular_material_index: 1.0,
  },
  {
    id: 51,
    type_id: 5,
    name: "Compost Waste",
    designation: "Compost bin",
    instruction:
      "Place all compostable waste, such as food scraps, yard waste, and biodegradable materials, in the compost bin. Ensure items are free from non-compostable contaminants.",
    reusable: "low",
    recyclable: "high",
    unit: "bag",
    weight_g: 3000,
    circular_material_index: 1.0,
  },
];
