module.exports=[
  {
    id: 1,
    name: "Plastic",
    image:"/images/image0.jpg",
    description: "Only 9% of all plastic waste ever produced has been recycled.",
    impact: "Recycling plastic reduces the need for new plastic production, conserving fossil fuels and reducing greenhouse gas emissions.",
    process: "Plastic is sorted by type and color, cleaned, shredded into flakes, melted, and then molded into new products.",
    going_to_landfill: 79,
    landfill_contribution: 18.5,
  
  },
  {
    id: 2,
    name: "Paper",
    image:"/images/image1.jpg",
    description: "Recycling one ton of paper saves 17 trees and 7,000 gallons of water.",
    impact: "Recycling paper helps reduce deforestation, save water, and decrease energy consumption compared to producing new paper from raw materials.",
    process: "It involves collecting, breaking down, and processing paper fibers to create pulp, which is then used to make new paper.",
    going_to_landfill: 25,
    landfill_contribution: 25.9,
  },
  {
    id: 3,
    name: "Glass",
    image:"/images/image2.jpg",
    process: "Glass is sorted by color, cleaned, crushed into cullet, melted, and then molded into new glass products.",
    impact: "Recycling glass reduces the need for raw materials and energy, lowering environmental impact and supporting sustainable manufacturing.",
    description: "Glass can be recycled indefinitely without losing its quality or purity.",
    going_to_landfill: 28,
    landfill_contribution: 5.3,

  },
  {
    id: 4,
    name: "Metal",
    image:"/images/image3.jpg",
    description: "Recycling aluminum saves 95% of the energy needed to produce new aluminum from raw materials.",
    impact: "Recycling metal reduces the need for new materials, conserving fossil fuels and reducing greenhouse gas emissions.",
    process: "Metals are sorted, cleaned, shredded, melted in a furnace, and then cast into new products.",
    going_to_landfill: 12,
    landfill_contribution: 9.0,
  },
  {
    id: 5,
    name: "Organic Waste",
    image:"/images/image4.jpg",
    description: "Food waste makes up about 24% of all municipal solid waste in landfills.",
    impact: "Recycling organic waste reduces the need for new materials, conserving fossil fuels and reducing greenhouse gas emissions.",
    process: "Organic waste is decomposed through aerobic processes to produce compost, which can be used as a soil amendment.",
    going_to_landfill: 24,
    landfill_contribution: 22.0,
  },
  {
    id: 6,
    name: "Electronics",
    image:"/images/image5.jpg",
    description: "E-waste represents only 2% in landfills, but it equals 70% of overall toxic waste.",
    impact: "Recycling electronic waste reduces the need for new materials, conserving fossil fuels and reducing greenhouse gas emissions.",
    process: "Electronics are disassembled, hazardous materials are removed, and components such as metals and plastics are separated and recycled.",
    going_to_landfill: 80,
    landfill_contribution: 1.4,
  },
  {
    id: 7,
    name: "Textiles",
    image:"/images/image6.jpg",
    description: "The average person throws away about 70 pounds of clothing each year.",
    impact: "Recycling textile reduces the need for new materials, conserving fossil fuels and reducing greenhouse gas emissions.",
    process: "Textiles are sorted by type and color, cleaned, shredded, and processed into fibers that can be spun into new yarn or used for insulation and other products.",
    going_to_landfill: 85,
    landfill_contribution: 6.3,
  }
]